spring:
  application:
    name: banking-service

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bankingdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: auto-create
        globally_quoted_identifiers: true


  flyway:
    enabled: true
    locations: classpath:/db/migration
    baselineOnMigrate: true
    baseline-version: 1

# App properties
app:
  currency: EUR
  iban:
    country-code: LU
    bank-code: 0019
    account-number-length: 12
  exchange-rate-url: https://api.exchangerate-api.com/v4/latest/
